export const regions = [
  { label: 'Kota Banda Aceh', value: 'Kota Banda Aceh' },
  { label: 'Kota Sabang', value: 'Kota Sabang' },
  { label: 'Kota Lhokseumawe', value: 'Kota Lhokseumawe' },
  { label: 'Kota Langsa', value: 'Kota Langsa' },
  { label: 'Kota Subulussalam', value: 'Kota Subulussalam' },
  { label: 'Kab. Aceh Selatan', value: 'Kab. Aceh Selatan' },
  { label: 'Kab. Aceh Tenggara', value: 'Kab. Aceh Tenggara' },
  { label: 'Kab. Aceh Timur', value: 'Kab. Aceh Timur' },
  { label: 'Kab. Aceh Tengah', value: 'Kab. Aceh Tengah' },
  { label: 'Kab. Aceh Barat', value: 'Kab. Aceh Barat' },
  { label: 'Kab. Aceh Besar', value: 'Kab. Aceh Besar' },
  { label: 'Kab. Pidie', value: 'Kab. Pidie' },
  { label: 'Kab. Aceh Utara', value: 'Kab. Aceh Utara' },
  { label: 'Kab. Simeulue', value: 'Kab. Simeulue' },
  { label: 'Kab. Aceh Singkil', value: 'Kab. Aceh Singkil' },
  { label: 'Kab. Bireun', value: 'Kab. Bireun' },
  { label: 'Kab. Aceh Barat Daya', value: 'Kab. Aceh Barat Daya' },
  { label: 'Kab. Gayo Lues', value: 'Kab. Gayo Lues' },
  { label: 'Kab. Aceh Jaya', value: 'Kab. Aceh Jaya' },
  { label: 'Kab. Nagan Raya', value: 'Kab. Nagan Raya' },
  { label: 'Kab. Aceh Tamiang', value: 'Kab. Aceh Tamiang' },
  { label: 'Kab. Bener Meriah', value: 'Kab. Bener Meriah' },
  { label: 'Kab. Pidie Jaya', value: 'Kab. Pidie Jaya' },
  { label: 'Kota Medan', value: 'Kota Medan' },
  { label: 'Kota Pematang Siantar', value: 'Kota Pematang Siantar' },
  { label: 'Kota Sibolga', value: 'Kota Sibolga' },
  { label: 'Kota Tanjung Balai', value: 'Kota Tanjung Balai' },
  { label: 'Kota Binjai', value: 'Kota Binjai' },
  { label: 'Kota Tebing Tinggi', value: 'Kota Tebing Tinggi' },
  { label: 'Kota Padang Sidempuan', value: 'Kota Padang Sidempuan' },
  { label: 'Kota Gunung Sitoli', value: 'Kota Gunung Sitoli' },
  { label: 'Kab. Serdang Bedagai', value: 'Kab. Serdang Bedagai' },
  { label: 'Kab. Samosir ', value: 'Kab. Samosir ' },
  { label: 'Kab. Humbang Hasundutan', value: 'Kab. Humbang Hasundutan' },
  { label: 'Kab. Pakpak Bharat', value: 'Kab. Pakpak Bharat' },
  { label: 'Kab. Nias Selatan', value: 'Kab. Nias Selatan' },
  { label: 'Kab. Mandailing Natal', value: 'Kab. Mandailing Natal' },
  { label: 'Kab. Toba Samosir', value: 'Kab. Toba Samosir' },
  { label: 'Kab. Dairi', value: 'Kab. Dairi' },
  { label: 'Kab. Labuhan Batu', value: 'Kab. Labuhan Batu' },
  { label: 'Kab. Asahan', value: 'Kab. Asahan' },
  { label: 'Kab. Simalungun', value: 'Kab. Simalungun' },
  { label: 'Kab. Deli Serdang', value: 'Kab. Deli Serdang' },
  { label: 'Kab. Karo', value: 'Kab. Karo' },
  { label: 'Kab. Langkat', value: 'Kab. Langkat' },
  { label: 'Kab. Nias', value: 'Kab. Nias' },
  { label: 'Kab. Tapanuli Selatan', value: 'Kab. Tapanuli Selatan' },
  { label: 'Kab. Tapanuli Utara', value: 'Kab. Tapanuli Utara' },
  { label: 'Kab. Tapanuli Tengah', value: 'Kab. Tapanuli Tengah' },
  { label: 'Kab. Batu Bara', value: 'Kab. Batu Bara' },
  { label: 'Kab. Padang Lawas Utara', value: 'Kab. Padang Lawas Utara' },
  { label: 'Kab. Padang Lawas', value: 'Kab. Padang Lawas' },
  { label: 'Kab. Labuhanbatu Selatan', value: 'Kab. Labuhanbatu Selatan' },
  { label: 'Kab. Labuhanbatu Utara', value: 'Kab. Labuhanbatu Utara' },
  { label: 'Kab. Nias Utara', value: 'Kab. Nias Utara' },
  { label: 'Kab. Nias Barat', value: 'Kab. Nias Barat' },
  { label: 'Kota Padang', value: 'Kota Padang' },
  { label: 'Kota Solok', value: 'Kota Solok' },
  { label: 'Kota Sawhlunto', value: 'Kota Sawhlunto' },
  { label: 'Kota Padang Panjang', value: 'Kota Padang Panjang' },
  { label: 'Kota Bukittinggi', value: 'Kota Bukittinggi' },
  { label: 'Kota Payakumbuh', value: 'Kota Payakumbuh' },
  { label: 'Kota Pariaman', value: 'Kota Pariaman' },
  { label: 'Kab. Pasaman Barat', value: 'Kab. Pasaman Barat' },
  { label: 'Kab. Solok Selatan', value: 'Kab. Solok Selatan' },
  { label: 'Kab. Dharmasraya', value: 'Kab. Dharmasraya' },
  { label: 'Kab. Kepulauan Mentawai', value: 'Kab. Kepulauan Mentawai' },
  { label: 'Kab. Pasaman', value: 'Kab. Pasaman' },
  { label: 'Kab. Lima Puluh Kota', value: 'Kab. Lima Puluh Kota' },
  { label: 'Kab. Agam', value: 'Kab. Agam' },
  { label: 'Kab. Padang Pariaman', value: 'Kab. Padang Pariaman' },
  { label: 'Kab. Tanah Datar', value: 'Kab. Tanah Datar' },
  { label: 'Kab. Sijunjung', value: 'Kab. Sijunjung' },
  { label: 'Kab. Solok', value: 'Kab. Solok' },
  { label: 'Kab. Pesisir Selatan', value: 'Kab. Pesisir Selatan' },
  { label: 'Kota Pekan Baru', value: 'Kota Pekan Baru' },
  { label: 'Kota Dumai', value: 'Kota Dumai' },
  { label: 'Kab. Kepulauan Meranti', value: 'Kab. Kepulauan Meranti' },
  { label: 'Kab. Kuantan Singingi', value: 'Kab. Kuantan Singingi' },
  { label: 'Kab. Siak', value: 'Kab. Siak' },
  { label: 'Kab. Rokan Hilir', value: 'Kab. Rokan Hilir' },
  { label: 'Kab. Rokan Hulu', value: 'Kab. Rokan Hulu' },
  { label: 'Kab. Pelalawan', value: 'Kab. Pelalawan' },
  { label: 'Kab. Indragiri Hilir', value: 'Kab. Indragiri Hilir' },
  { label: 'Kab. Bengkalis', value: 'Kab. Bengkalis' },
  { label: 'Kab. Indragiri Hulu', value: 'Kab. Indragiri Hulu' },
  { label: 'Kab. Kampar', value: 'Kab. Kampar' },
  { label: 'Kota Jambi', value: 'Kota Jambi' },
  { label: 'Kota Sungai Penuh', value: 'Kota Sungai Penuh' },
  { label: 'Kab. Tebo', value: 'Kab. Tebo' },
  { label: 'Kab. Bungo', value: 'Kab. Bungo' },
  { label: 'Kab. Tanjung Jabung Timur', value: 'Kab. Tanjung Jabung Timur' },
  { label: 'Kab. Tanjung Jabung Barat', value: 'Kab. Tanjung Jabung Barat' },
  { label: 'Kab. Muaro Jambi', value: 'Kab. Muaro Jambi' },
  { label: 'Kab. Batanghari', value: 'Kab. Batanghari' },
  { label: 'Kab. Sarolangun', value: 'Kab. Sarolangun' },
  { label: 'Kab. Merangin', value: 'Kab. Merangin' },
  { label: 'Kab. Kerinci', value: 'Kab. Kerinci' },
  { label: 'Kota Palembang', value: 'Kota Palembang' },
  { label: 'Kota Pagar Alam', value: 'Kota Pagar Alam' },
  { label: 'Kota Lubuk Linggau', value: 'Kota Lubuk Linggau' },
  { label: 'Kota Prabumulih', value: 'Kota Prabumulih' },
  { label: 'Kab. Musi Rawas Utara', value: 'Kab. Musi Rawas Utara' },
  { label: 'Kab. Penukal Abab Lematang Ilir', value: 'Kab. Penukal Abab Lematang Ilir' },
  { label: 'Kab. Empat Lawang', value: 'Kab. Empat Lawang' },
  { label: 'Kab. Ogan Ilir ', value: 'Kab. Ogan Ilir ' },
  { label: 'Kab. Ogan Komering Ulu Selatan ', value: 'Kab. Ogan Komering Ulu Selatan ' },
  { label: 'Kab. Ogan Komering Ulu Timur ', value: 'Kab. Ogan Komering Ulu Timur ' },
  { label: 'Kab. Banyuasin', value: 'Kab. Banyuasin' },
  { label: 'Kab. Musi Banyuasin', value: 'Kab. Musi Banyuasin' },
  { label: 'Kab. Musi Rawas', value: 'Kab. Musi Rawas' },
  { label: 'Kab. Lahat', value: 'Kab. Lahat' },
  { label: 'Kab. Muara Enim', value: 'Kab. Muara Enim' },
  { label: 'Kab. Ogan Komering Ilir', value: 'Kab. Ogan Komering Ilir' },
  { label: 'Kab. Ogan Komering Ulu', value: 'Kab. Ogan Komering Ulu' },
  { label: 'Kota Bengkulu', value: 'Kota Bengkulu' },
  { label: 'Kab. Bengkulu Tengah', value: 'Kab. Bengkulu Tengah' },
  { label: 'Kab. Kepahiang ', value: 'Kab. Kepahiang ' },
  { label: 'Kab. Lebong', value: 'Kab. Lebong' },
  { label: 'Kab. Muko Muko', value: 'Kab. Muko Muko' },
  { label: 'Kab. Seluma', value: 'Kab. Seluma' },
  { label: 'Kab. Kaur', value: 'Kab. Kaur' },
  { label: 'Kab. Bengkulu Utara', value: 'Kab. Bengkulu Utara' },
  { label: 'Kab. Rejang Lebong', value: 'Kab. Rejang Lebong' },
  { label: 'Kab. Bengkulu Selatan', value: 'Kab. Bengkulu Selatan' },
  { label: 'Kota Bandar Lampung', value: 'Kota Bandar Lampung' },
  { label: 'Kota Metro', value: 'Kota Metro' },
  { label: 'Kab. Pesisir Barat', value: 'Kab. Pesisir Barat' },
  { label: 'Kab. Tulangbawang Barat', value: 'Kab. Tulangbawang Barat' },
  { label: 'Kab. Mesuji', value: 'Kab. Mesuji' },
  { label: 'Kab. Pringsewu', value: 'Kab. Pringsewu' },
  { label: 'Kab. Pesawaran', value: 'Kab. Pesawaran' },
  { label: 'Kab. Way Kanan', value: 'Kab. Way Kanan' },
  { label: 'Kab. Lampung Timur', value: 'Kab. Lampung Timur' },
  { label: 'Kab. Tanggamus', value: 'Kab. Tanggamus' },
  { label: 'Kab. Tulang Bawang', value: 'Kab. Tulang Bawang' },
  { label: 'Kab. Lampung Barat', value: 'Kab. Lampung Barat' },
  { label: 'Kab. Lampung Utara', value: 'Kab. Lampung Utara' },
  { label: 'Kab. Lampung Tengah', value: 'Kab. Lampung Tengah' },
  { label: 'Kab. Lampung Selatan', value: 'Kab. Lampung Selatan' },
  { label: 'Kota Pangkal Pinang', value: 'Kota Pangkal Pinang' },
  { label: 'Kab. Belitung Timur', value: 'Kab. Belitung Timur' },
  { label: 'Kab. Bangka Barat', value: 'Kab. Bangka Barat' },
  { label: 'Kab. Bangka Tengah', value: 'Kab. Bangka Tengah' },
  { label: 'Kab. Bangka Selatan', value: 'Kab. Bangka Selatan' },
  { label: 'Kab. Belitung', value: 'Kab. Belitung' },
  { label: 'Kab. Bangka', value: 'Kab. Bangka' },
  { label: 'Kota Batam', value: 'Kota Batam' },
  { label: 'Kota Tanjung Pinang', value: 'Kota Tanjung Pinang' },
  { label: 'Kab. Kepulauan Anambas', value: 'Kab. Kepulauan Anambas' },
  { label: 'Kab. Lingga', value: 'Kab. Lingga' },
  { label: 'Kab. Natuna', value: 'Kab. Natuna' },
  { label: 'Kab. Karimun', value: 'Kab. Karimun' },
  { label: 'Kab. Bintan', value: 'Kab. Bintan' },
  { label: 'Kota Jakarta Timur', value: 'Kota Jakarta Timur' },
  { label: 'Kota Jakarta Selatan', value: 'Kota Jakarta Selatan' },
  { label: 'Kota Jakarta Barat', value: 'Kota Jakarta Barat' },
  { label: 'Kota Jakarta Utara', value: 'Kota Jakarta Utara' },
  { label: 'Kota Jakarta Pusat', value: 'Kota Jakarta Pusat' },
  { label: 'Kab. Kepulauan Seribu', value: 'Kab. Kepulauan Seribu' },
  { label: 'Kota Bandung', value: 'Kota Bandung' },
  { label: 'Kota Banjar', value: 'Kota Banjar' },
  { label: 'Kota Tasikmalaya', value: 'Kota Tasikmalaya' },
  { label: 'Kota Cimahi', value: 'Kota Cimahi' },
  { label: 'Kota Depok', value: 'Kota Depok' },
  { label: 'Kota Bekasi', value: 'Kota Bekasi' },
  { label: 'Kota Cirebon', value: 'Kota Cirebon' },
  { label: 'Kota Sukabumi', value: 'Kota Sukabumi' },
  { label: 'Kota Bogor', value: 'Kota Bogor' },
  { label: 'Kab. Pangandaran', value: 'Kab. Pangandaran' },
  { label: 'Kab. Bandung Barat', value: 'Kab. Bandung Barat' },
  { label: 'Kab. Bekasi', value: 'Kab. Bekasi' },
  { label: 'Kab. Karawang', value: 'Kab. Karawang' },
  { label: 'Kab. Purwakarta', value: 'Kab. Purwakarta' },
  { label: 'Kab. Subang', value: 'Kab. Subang' },
  { label: 'Kab. Indramayu', value: 'Kab. Indramayu' },
  { label: 'Kab. Sumedang', value: 'Kab. Sumedang' },
  { label: 'Kab. Majalengka', value: 'Kab. Majalengka' },
  { label: 'Kab. Cirebon', value: 'Kab. Cirebon' },
  { label: 'Kab. Kuningan', value: 'Kab. Kuningan' },
  { label: 'Kab. Ciamis', value: 'Kab. Ciamis' },
  { label: 'Kab. Tasikmalaya', value: 'Kab. Tasikmalaya' },
  { label: 'Kab. Garut', value: 'Kab. Garut' },
  { label: 'Kab. Bandung', value: 'Kab. Bandung' },
  { label: 'Kab. Cianjur', value: 'Kab. Cianjur' },
  { label: 'Kab. Sukabumi', value: 'Kab. Sukabumi' },
  { label: 'Kab. Bogor', value: 'Kab. Bogor' },
  { label: 'Kota Semarang', value: 'Kota Semarang' },
  { label: 'Kota Tegal', value: 'Kota Tegal' },
  { label: 'Kota Pekalongan', value: 'Kota Pekalongan' },
  { label: 'Kota Salatiga', value: 'Kota Salatiga' },
  { label: 'Kota Surakarta', value: 'Kota Surakarta' },
  { label: 'Kota Magelang', value: 'Kota Magelang' },
  { label: 'Kab. Brebes', value: 'Kab. Brebes' },
  { label: 'Kab. Tegal', value: 'Kab. Tegal' },
  { label: 'Kab. Pemalang', value: 'Kab. Pemalang' },
  { label: 'Kab. Pekalongan', value: 'Kab. Pekalongan' },
  { label: 'Kab. Batang', value: 'Kab. Batang' },
  { label: 'Kab. Kendal', value: 'Kab. Kendal' },
  { label: 'Kab. Temanggung', value: 'Kab. Temanggung' },
  { label: 'Kab. Semarang', value: 'Kab. Semarang' },
  { label: 'Kab. Demak', value: 'Kab. Demak' },
  { label: 'Kab. Jepara', value: 'Kab. Jepara' },
  { label: 'Kab. Kudus', value: 'Kab. Kudus' },
  { label: 'Kab. Pati', value: 'Kab. Pati' },
  { label: 'Kab. Rembang', value: 'Kab. Rembang' },
  { label: 'Kab. Blora', value: 'Kab. Blora' },
  { label: 'Kab. Grobogan', value: 'Kab. Grobogan' },
  { label: 'Kab. Sragen', value: 'Kab. Sragen' },
  { label: 'Kab. Karanganyar', value: 'Kab. Karanganyar' },
  { label: 'Kab. Wonogiri', value: 'Kab. Wonogiri' },
  { label: 'Kab. Sukoharjo', value: 'Kab. Sukoharjo' },
  { label: 'Kab. Klaten', value: 'Kab. Klaten' },
  { label: 'Kab. Boyolali', value: 'Kab. Boyolali' },
  { label: 'Kab. Magelang', value: 'Kab. Magelang' },
  { label: 'Kab. Wonosobo', value: 'Kab. Wonosobo' },
  { label: 'Kab. Purworejo', value: 'Kab. Purworejo' },
  { label: 'Kab. Kebumen', value: 'Kab. Kebumen' },
  { label: 'Kab. Banjarnegara', value: 'Kab. Banjarnegara' },
  { label: 'Kab. Purbalingga', value: 'Kab. Purbalingga' },
  { label: 'Kab. Banyumas', value: 'Kab. Banyumas' },
  { label: 'Kab. Cilacap', value: 'Kab. Cilacap' },
  { label: 'Kota Yogyakarta', value: 'Kota Yogyakarta' },
  { label: 'Kab. Sleman', value: 'Kab. Sleman' },
  { label: 'Kab. Gunung Kidul', value: 'Kab. Gunung Kidul' },
  { label: 'Kab. Bantul', value: 'Kab. Bantul' },
  { label: 'Kab. Kulon Progo', value: 'Kab. Kulon Progo' },
  { label: 'Kota Surabaya', value: 'Kota Surabaya' },
  { label: 'Kota Batu', value: 'Kota Batu' },
  { label: 'Kota Madiun', value: 'Kota Madiun' },
  { label: 'Kota Mojokerto', value: 'Kota Mojokerto' },
  { label: 'Kota Pasuruan', value: 'Kota Pasuruan' },
  { label: 'Kota Probolinggo', value: 'Kota Probolinggo' },
  { label: 'Kota Malang', value: 'Kota Malang' },
  { label: 'Kota Blitar', value: 'Kota Blitar' },
  { label: 'Kota Kediri', value: 'Kota Kediri' },
  { label: 'Kab. Sumenep', value: 'Kab. Sumenep' },
  { label: 'Kab. Pamekasan', value: 'Kab. Pamekasan' },
  { label: 'Kab. Sampang', value: 'Kab. Sampang' },
  { label: 'Kab. Bangkalan', value: 'Kab. Bangkalan' },
  { label: 'Kab. Gresik', value: 'Kab. Gresik' },
  { label: 'Kab. Lamongan', value: 'Kab. Lamongan' },
  { label: 'Kab. Tuban', value: 'Kab. Tuban' },
  { label: 'Kab. Bojonegoro', value: 'Kab. Bojonegoro' },
  { label: 'Kab. Ngawi', value: 'Kab. Ngawi' },
  { label: 'Kab. Magetan', value: 'Kab. Magetan' },
  { label: 'Kab. Madiun', value: 'Kab. Madiun' },
  { label: 'Kab. Nganjuk', value: 'Kab. Nganjuk' },
  { label: 'Kab. Jombang', value: 'Kab. Jombang' },
  { label: 'Kab. Mojokerto', value: 'Kab. Mojokerto' },
  { label: 'Kab. Sidoarjo', value: 'Kab. Sidoarjo' },
  { label: 'Kab. Pasuruan', value: 'Kab. Pasuruan' },
  { label: 'Kab. Probolinggo', value: 'Kab. Probolinggo' },
  { label: 'Kab. Situbondo', value: 'Kab. Situbondo' },
  { label: 'Kab. Bondowoso', value: 'Kab. Bondowoso' },
  { label: 'Kab. Banyuwangi', value: 'Kab. Banyuwangi' },
  { label: 'Kab. Jember', value: 'Kab. Jember' },
  { label: 'Kab. Lumajang', value: 'Kab. Lumajang' },
  { label: 'Kab. Malang', value: 'Kab. Malang' },
  { label: 'Kab. Kediri', value: 'Kab. Kediri' },
  { label: 'Kab. Blitar', value: 'Kab. Blitar' },
  { label: 'Kab. Tulungagung', value: 'Kab. Tulungagung' },
  { label: 'Kab. Trenggalek', value: 'Kab. Trenggalek' },
  { label: 'Kab. Ponorogo', value: 'Kab. Ponorogo' },
  { label: 'Kab. Pacitan', value: 'Kab. Pacitan' },
  { label: 'Kota Serang', value: 'Kota Serang' },
  { label: 'Kota Cilegon', value: 'Kota Cilegon' },
  { label: 'Kota Tangerang', value: 'Kota Tangerang' },
  { label: 'Kota Tangerang Selatan', value: 'Kota Tangerang Selatan' },
  { label: 'Kab. Serang', value: 'Kab. Serang' },
  { label: 'Kab. Tangerang', value: 'Kab. Tangerang' },
  { label: 'Kab. Lebak', value: 'Kab. Lebak' },
  { label: 'Kab. Pandeglang', value: 'Kab. Pandeglang' },
  { label: 'Kota Denpasar', value: 'Kota Denpasar' },
  { label: 'Kab. Buleleng', value: 'Kab. Buleleng' },
  { label: 'Kab. Karangasem', value: 'Kab. Karangasem' },
  { label: 'Kab. Bangli', value: 'Kab. Bangli' },
  { label: 'Kab. Klungkung', value: 'Kab. Klungkung' },
  { label: 'Kab. Gianyar', value: 'Kab. Gianyar' },
  { label: 'Kab. Badung', value: 'Kab. Badung' },
  { label: 'Kab. Tabanan', value: 'Kab. Tabanan' },
  { label: 'Kab. Jembrana', value: 'Kab. Jembrana' },
  { label: 'Kota Mataram', value: 'Kota Mataram' },
  { label: 'Kota Bima', value: 'Kota Bima' },
  { label: 'Kab. Lombok Utara', value: 'Kab. Lombok Utara' },
  { label: 'Kab. Sumbawa Barat', value: 'Kab. Sumbawa Barat' },
  { label: 'Kab. Bima', value: 'Kab. Bima' },
  { label: 'Kab. Dompu', value: 'Kab. Dompu' },
  { label: 'Kab. Sumbawa', value: 'Kab. Sumbawa' },
  { label: 'Kab. Lombok Timur', value: 'Kab. Lombok Timur' },
  { label: 'Kab. Lombok Tengah', value: 'Kab. Lombok Tengah' },
  { label: 'Kab. Lombok Barat', value: 'Kab. Lombok Barat' },
  { label: 'Kota Kupang', value: 'Kota Kupang' },
  { label: 'Kab. Malaka', value: 'Kab. Malaka' },
  { label: 'Kab. Sabu Raijua', value: 'Kab. Sabu Raijua' },
  { label: 'Kab. Manggarai Timur', value: 'Kab. Manggarai Timur' },
  { label: 'Kab. Sumba Barat Daya', value: 'Kab. Sumba Barat Daya' },
  { label: 'Kab. Sumba Tengah', value: 'Kab. Sumba Tengah' },
  { label: 'Kab. Nagekeo', value: 'Kab. Nagekeo' },
  { label: 'Kab. Manggarai Barat', value: 'Kab. Manggarai Barat' },
  { label: 'Kab. Rote Ndao', value: 'Kab. Rote Ndao' },
  { label: 'Kab. Lembata', value: 'Kab. Lembata' },
  { label: 'Kab. Sumba Barat', value: 'Kab. Sumba Barat' },
  { label: 'Kab. Sumba Timur', value: 'Kab. Sumba Timur' },
  { label: 'Kab. Manggarai', value: 'Kab. Manggarai' },
  { label: 'Kab. Ngada', value: 'Kab. Ngada' },
  { label: 'Kab. Ende', value: 'Kab. Ende' },
  { label: 'Kab. Sikka', value: 'Kab. Sikka' },
  { label: 'Kab. Flores Timur', value: 'Kab. Flores Timur' },
  { label: 'Kab. Alor', value: 'Kab. Alor' },
  { label: 'Kab. Belu', value: 'Kab. Belu' },
  { label: 'Kab. Timor Tengah Utara', value: 'Kab. Timor Tengah Utara' },
  { label: 'Kab. Timor Tengah Selatan', value: 'Kab. Timor Tengah Selatan' },
  { label: 'Kab. Kupang', value: 'Kab. Kupang' },
  { label: 'Kota Pontianak', value: 'Kota Pontianak' },
  { label: 'Kota Singkawang', value: 'Kota Singkawang' },
  { label: 'Kab. Kubu Raya', value: 'Kab. Kubu Raya' },
  { label: 'Kab. Kayong Utara', value: 'Kab. Kayong Utara' },
  { label: 'Kab. Sekadau', value: 'Kab. Sekadau' },
  { label: 'Kab. Melawi', value: 'Kab. Melawi' },
  { label: 'Kab. Landak', value: 'Kab. Landak' },
  { label: 'Kab. Bengkayang', value: 'Kab. Bengkayang' },
  { label: 'Kab. Kapuas Hulu', value: 'Kab. Kapuas Hulu' },
  { label: 'Kab. Sintang', value: 'Kab. Sintang' },
  { label: 'Kab. Ketapang', value: 'Kab. Ketapang' },
  { label: 'Kab. Sanggau', value: 'Kab. Sanggau' },
  { label: 'Kab. Mempawah', value: 'Kab. Mempawah' },
  { label: 'Kab. Sambas', value: 'Kab. Sambas' },
  { label: 'Kota Palangkaraya', value: 'Kota Palangkaraya' },
  { label: 'Kab. Barito Timur', value: 'Kab. Barito Timur' },
  { label: 'Kab. Murung Raya', value: 'Kab. Murung Raya' },
  { label: 'Kab. Pulang Pisau', value: 'Kab. Pulang Pisau' },
  { label: 'Kab. Gunung Mas', value: 'Kab. Gunung Mas' },
  { label: 'Kab. Lamandau', value: 'Kab. Lamandau' },
  { label: 'Kab. Sukamara', value: 'Kab. Sukamara' },
  { label: 'Kab. Seruyan', value: 'Kab. Seruyan' },
  { label: 'Kab. Katingan', value: 'Kab. Katingan' },
  { label: 'Kab. Barito Utara', value: 'Kab. Barito Utara' },
  { label: 'Kab. Barito Selatan', value: 'Kab. Barito Selatan' },
  { label: 'Kab. Kapuas', value: 'Kab. Kapuas' },
  { label: 'Kab. Kotawaringin Timur', value: 'Kab. Kotawaringin Timur' },
  { label: 'Kab. Kotawaringin Barat', value: 'Kab. Kotawaringin Barat' },
  { label: 'Kota Banjarmasin', value: 'Kota Banjarmasin' },
  { label: 'Kota Banjarbaru', value: 'Kota Banjarbaru' },
  { label: 'Kab. Balangan', value: 'Kab. Balangan' },
  { label: 'Kab. Tanah Bambu', value: 'Kab. Tanah Bambu' },
  { label: 'Kab. Tabalong', value: 'Kab. Tabalong' },
  { label: 'Kab. Hulu Sungai Utara', value: 'Kab. Hulu Sungai Utara' },
  { label: 'Kab. Hulu Sungai Tengah', value: 'Kab. Hulu Sungai Tengah' },
  { label: 'Kab. Hulu Sungai Selatan', value: 'Kab. Hulu Sungai Selatan' },
  { label: 'Kab. Tapin', value: 'Kab. Tapin' },
  { label: 'Kab. Barito Kuala', value: 'Kab. Barito Kuala' },
  { label: 'Kab. Banjar', value: 'Kab. Banjar' },
  { label: 'Kab. Kotabaru', value: 'Kab. Kotabaru' },
  { label: 'Kab. Tanah Laut', value: 'Kab. Tanah Laut' },
  { label: 'Kota Samarinda', value: 'Kota Samarinda' },
  { label: 'Kota Bontang', value: 'Kota Bontang' },
  { label: 'Kota Balikpapan', value: 'Kota Balikpapan' },
  { label: 'Kab. Mahakam Ulu', value: 'Kab. Mahakam Ulu' },
  { label: 'Kab. Penajam Paser Utara', value: 'Kab. Penajam Paser Utara' },
  { label: 'Kab. Kutai Timur', value: 'Kab. Kutai Timur' },
  { label: 'Kab. Kutai Barat', value: 'Kab. Kutai Barat' },
  { label: 'Kab. Berau', value: 'Kab. Berau' },
  { label: 'Kab. Kutai Kertanegara', value: 'Kab. Kutai Kertanegara' },
  { label: 'Kab. Paser', value: 'Kab. Paser' },
  { label: 'Kota Tarakan', value: 'Kota Tarakan' },
  { label: 'Kab. Tana Tidung', value: 'Kab. Tana Tidung' },
  { label: 'Kab. Nunukan', value: 'Kab. Nunukan' },
  { label: 'Kab. Malinau', value: 'Kab. Malinau' },
  { label: 'Kab. Bulungan', value: 'Kab. Bulungan' },
  { label: 'Kota Manado', value: 'Kota Manado' },
  { label: 'Kota Tomohon', value: 'Kota Tomohon' },
  { label: 'Kota Bitung', value: 'Kota Bitung' },
  { label: 'Kota Kotamobagu', value: 'Kota Kotamobagu' },
  { label: 'Kab. Bolaang Mangondow Selatan', value: 'Kab. Bolaang Mangondow Selatan' },
  { label: 'Kab. Bolaang Mangondow Timur', value: 'Kab. Bolaang Mangondow Timur' },
  { label: 'Kab. Kepulauan Siau Tagulandang Biaro', value: 'Kab. Kepulauan Siau Tagulandang Biaro' },
  { label: 'Kab. Bolaang Mangondow Utara', value: 'Kab. Bolaang Mangondow Utara' },
  { label: 'Kab. Minahasa Tenggara', value: 'Kab. Minahasa Tenggara' },
  { label: 'Kab. Minahasa Utara', value: 'Kab. Minahasa Utara' },
  { label: 'Kab. Minahasa Selatan', value: 'Kab. Minahasa Selatan' },
  { label: 'Kab. Kepulauan Talaud', value: 'Kab. Kepulauan Talaud' },
  { label: 'Kab. Kepulauan Sangihe', value: 'Kab. Kepulauan Sangihe' },
  { label: 'Kab. Minahasa', value: 'Kab. Minahasa' },
  { label: 'Kab. Bolaang Mangondow', value: 'Kab. Bolaang Mangondow' },
  { label: 'Kota Palu', value: 'Kota Palu' },
  { label: 'Kab. Morowali Utara', value: 'Kab. Morowali Utara' },
  { label: 'Kab. Banggai Laut', value: 'Kab. Banggai Laut' },
  { label: 'Kab. Sigi', value: 'Kab. Sigi' },
  { label: 'Kab. Tojo Una-Una', value: 'Kab. Tojo Una-Una' },
  { label: 'Kab. Parigi Moutong', value: 'Kab. Parigi Moutong' },
  { label: 'Kab. Banggai Kepulauan', value: 'Kab. Banggai Kepulauan' },
  { label: 'Kab. Morowali', value: 'Kab. Morowali' },
  { label: 'Kab. Buol', value: 'Kab. Buol' },
  { label: 'Kab. Toli-Toli', value: 'Kab. Toli-Toli' },
  { label: 'Kab. Donggala', value: 'Kab. Donggala' },
  { label: 'Kab. Poso', value: 'Kab. Poso' },
  { label: 'Kab. Banggai', value: 'Kab. Banggai' },
  { label: 'Kota Makasar', value: 'Kota Makasar' },
  { label: 'Kota Palopo', value: 'Kota Palopo' },
  { label: 'Kota Pare Pare', value: 'Kota Pare Pare' },
  { label: 'Kab. Toraja Utara', value: 'Kab. Toraja Utara' },
  { label: 'Kab. Luwu Timur', value: 'Kab. Luwu Timur' },
  { label: 'Kab. Luwu Utara', value: 'Kab. Luwu Utara' },
  { label: 'Kab. Tana Toraja', value: 'Kab. Tana Toraja' },
  { label: 'Kab. Luwu', value: 'Kab. Luwu' },
  { label: 'Kab. Enrekang', value: 'Kab. Enrekang' },
  { label: 'Kab. Pinrang', value: 'Kab. Pinrang' },
  { label: 'Kab. Sidenreng Rappang', value: 'Kab. Sidenreng Rappang' },
  { label: 'Kab. Wajo', value: 'Kab. Wajo' },
  { label: 'Kab. Soppeng', value: 'Kab. Soppeng' },
  { label: 'Kab. Barru', value: 'Kab. Barru' },
  { label: 'Kab. Pangkajene Kepulauan', value: 'Kab. Pangkajene Kepulauan' },
  { label: 'Kab. Maros', value: 'Kab. Maros' },
  { label: 'Kab. Bone', value: 'Kab. Bone' },
  { label: 'Kab. Sinjai', value: 'Kab. Sinjai' },
  { label: 'Kab. Gowa', value: 'Kab. Gowa' },
  { label: 'Kab. Takalar', value: 'Kab. Takalar' },
  { label: 'Kab. Jeneponto', value: 'Kab. Jeneponto' },
  { label: 'Kab. Bantaeng', value: 'Kab. Bantaeng' },
  { label: 'Kab. Bulukumba', value: 'Kab. Bulukumba' },
  { label: 'Kab. Kepulauan Selayar', value: 'Kab. Kepulauan Selayar' },
  { label: 'Kota Kendari', value: 'Kota Kendari' },
  { label: 'Kota Bau Bau', value: 'Kota Bau Bau' },
  { label: 'Kab. Buton Selatan', value: 'Kab. Buton Selatan' },
  { label: 'Kab. Buton Tengah', value: 'Kab. Buton Tengah' },
  { label: 'Kab. Muna Barat', value: 'Kab. Muna Barat' },
  { label: 'Kab. Konawe Kepulauan', value: 'Kab. Konawe Kepulauan' },
  { label: 'Kab. Kolaka Timur', value: 'Kab. Kolaka Timur' },
  { label: 'Kab. Buton Utara', value: 'Kab. Buton Utara' },
  { label: 'Kab. Konawe Utara', value: 'Kab. Konawe Utara' },
  { label: 'Kab. Kolaka Utara', value: 'Kab. Kolaka Utara' },
  { label: 'Kab. Wakatobi', value: 'Kab. Wakatobi' },
  { label: 'Kab. Bombana', value: 'Kab. Bombana' },
  { label: 'Kab. Konawe Selatan', value: 'Kab. Konawe Selatan' },
  { label: 'Kab. Buton', value: 'Kab. Buton' },
  { label: 'Kab. Muna', value: 'Kab. Muna' },
  { label: 'Kab. Konawe', value: 'Kab. Konawe' },
  { label: 'Kab. Kolaka', value: 'Kab. Kolaka' },
  { label: 'Kota Gorontalo', value: 'Kota Gorontalo' },
  { label: 'Kab. Pohuwato', value: 'Kab. Pohuwato' },
  { label: 'Kab. Bone Bolango', value: 'Kab. Bone Bolango' },
  { label: 'Kab. Boalemo', value: 'Kab. Boalemo' },
  { label: 'Kab. Gorontalo', value: 'Kab. Gorontalo' },
  { label: 'Kab. Gorontalo Utara', value: 'Kab. Gorontalo Utara' },
  { label: 'Kab. Majene', value: 'Kab. Majene' },
  { label: 'Kab. Polowali Mandar', value: 'Kab. Polowali Mandar' },
  { label: 'Kab. Mamasa', value: 'Kab. Mamasa' },
  { label: 'Kab. Mamuju', value: 'Kab. Mamuju' },
  { label: 'Kab. Mamuju Utara', value: 'Kab. Mamuju Utara' },
  { label: 'Kab. Mamuju Tengah', value: 'Kab. Mamuju Tengah' },
  { label: 'Kota Ambon', value: 'Kota Ambon' },
  { label: 'Kota Tual', value: 'Kota Tual' },
  { label: 'Kab. Buru Selatan', value: 'Kab. Buru Selatan' },
  { label: 'Kab. Maluku Barat Daya', value: 'Kab. Maluku Barat Daya' },
  { label: 'Kab. Kepulauan Aru', value: 'Kab. Kepulauan Aru' },
  { label: 'Kab. Seram Bagian Barat', value: 'Kab. Seram Bagian Barat ' },
  { label: 'Kab. Seram Bagian Timur', value: 'Kab. Seram Bagian Timur' },
  { label: 'Kab. Buru', value: 'Kab. Buru' },
  { label: 'Kab. Maluku Tenggara Barat', value: 'Kab. Maluku Tenggara Barat' },
  { label: 'Kab. Maluku Tenggara', value: 'Kab. Maluku Tenggara' },
  { label: 'Kab. Maluku Tengah', value: 'Kab. Maluku Tengah' },
  { label: 'Kota Ternate', value: 'Kota Ternate' },
  { label: 'Kota Tidore Kepulauan', value: 'Kota Tidore Kepulauan' },
  { label: 'Kab. Pulau Taliabu', value: 'Kab. Pulau Taliabu' },
  { label: 'Kab. Pulau Morotai', value: 'Kab. Pulau Morotai' },
  { label: 'Kab. Halmahera Timur', value: 'Kab. Halmahera Timur' },
  { label: 'Kab. Kepulauan Sula', value: 'Kab. Kepulauan Sula' },
  { label: 'Kab. Halmahera Selatan', value: 'Kab. Halmahera Selatan' },
  { label: 'Kab. Halmahera Utara', value: 'Kab. Halmahera Utara' },
  { label: 'Kab. Halmahera Tengah', value: 'Kab. Halmahera Tengah' },
  { label: 'Kab. Halmahera Barat', value: 'Kab. Halmahera Barat' },
  { label: 'Kota Jayapura', value: 'Kota Jayapura' },
  { label: 'Kab. Deiyai', value: 'Kab. Deiyai' },
  { label: 'Kab. Intan Jaya', value: 'Kab. Intan Jaya' },
  { label: 'Kab. Dogiyai', value: 'Kab. Dogiyai' },
  { label: 'Kab. Puncak', value: 'Kab. Puncak' },
  { label: 'Kab. Nduga', value: 'Kab. Nduga' },
  { label: 'Kab. Lanny Jaya', value: 'Kab. Lanny Jaya' },
  { label: 'Kab. Yalimo', value: 'Kab. Yalimo' },
  { label: 'Kab. Mamberamo Tengah', value: 'Kab. Mamberamo Tengah' },
  { label: 'Kab. Mamberamo Raya', value: 'Kab. Mamberamo Raya' },
  { label: 'Kab. Supiori', value: 'Kab. Supiori' },
  { label: 'Kab. Asmat', value: 'Kab. Asmat' },
  { label: 'Kab. Mappi', value: 'Kab. Mappi' },
  { label: 'Kab. Boven Digoel', value: 'Kab. Boven Digoel' },
  { label: 'Kab. Waropen', value: 'Kab. Waropen' },
  { label: 'Kab. Tolikara', value: 'Kab. Tolikara' },
  { label: 'Kab. Yahukimo', value: 'Kab. Yahukimo' },
  { label: 'Kab. Pegunungan Bintang', value: 'Kab. Pegunungan Bintang' },
  { label: 'Kab. Keerom', value: 'Kab. Keerom' },
  { label: 'Kab. Sarmi', value: 'Kab. Sarmi' },
  { label: 'Kab. Mimika', value: 'Kab. Mimika' },
  { label: 'Kab. Paniai', value: 'Kab. Paniai' },
  { label: 'Kab. Puncak Jaya', value: 'Kab. Puncak Jaya' },
  { label: 'Kab. Biak Numfor', value: 'Kab. Biak Numfor' },
  { label: 'Kab. Kepulauan Yapen', value: 'Kab. Kepulauan Yapen' },
  { label: 'Kab. Nabire', value: 'Kab. Nabire' },
  { label: 'Kab. Jayapura', value: 'Kab. Jayapura' },
  { label: 'Kab. Jayawijaya', value: 'Kab. Jayawijaya' },
  { label: 'Kab. Merauke', value: 'Kab. Merauke' },
  { label: 'Kota Sorong', value: 'Kota Sorong' },
  { label: 'Kab. Pegunungan Arfak', value: 'Kab. Pegunungan Arfak' },
  { label: 'Kab. Manokwari Selatan', value: 'Kab. Manokwari Selatan' },
  { label: 'Kab. Maybrat', value: 'Kab. Maybrat' },
  { label: 'Kab. Tambrauw', value: 'Kab. Tambrauw' },
  { label: 'Kab. Kaimana', value: 'Kab. Kaimana' },
  { label: 'Kab. Teluk Wondama', value: 'Kab. Teluk Wondama' },
  { label: 'Kab. Teluk Bintuni', value: 'Kab. Teluk Bintuni' },
  { label: 'Kab. Raja Ampat', value: 'Kab. Raja Ampat' },
  { label: 'Kab. Sorong Selatan', value: 'Kab. Sorong Selatan' },
  { label: 'Kab. Fak Fak', value: 'Kab. Fak Fak' },
  { label: 'Kab. Manokwari', value: 'Kab. Manokwari' },
  { label: 'Kab. Sorong', value: 'Kab. Sorong' },
];

export default regions;
