// Auth
export const LOGIN_SUCCESS = '@LOGIN_SUCCESS';
export const LOGIN_FAILED = '@LOGIN_FAILED';
export const REGISTER_SUCCESS = '@REGISTER_SUCCESS';
export const REGISTER_FAILED = '@LREGISTER_FAILED';

// Profile
export const GET_USER_SUCCESS = '@GET_USER_SUCCESS';
export const GET_USER_FAILED = '@GET_USER_FAILED';
export const UPDATE_USER_SUCCESS = '@UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = '@UPDATE_USER_FAILED';
export const CHANGE_PASSWORD_SUCCESS = '@CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = '@CHANGE_PASSWORD_FAILED';

// Global
export const LOGOUT = '@LOGOUT';
export const LOADING = '@LOADING';
export const REFRESH = '@REFRESH';

// Buyer
export const GET_PRODUCT_SUCCESS = '@GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = '@GET_PRODUCT_FAILED';
export const GET_DETAIL_PRODUCT_SUCCESS = '@GET_DETAIL_PRODUCT_SUCCESS';

// POST BID
export const BID_PRODUCT_SUCCESS = '@BID_PRODUCT_SUCCESS';
export const BID_PRODUCT_FAILED = '@BID_PRODUCT_FAILED';

// GET BID
export const GET_ALL_BID_SUCCESS = '@GET_ALL_BID_SUCCESS';
export const GET_ALL_BID_FAILED = '@GET_ALL_BID_FAILED';

// Seller
export const GET_CATEGORY_SUCCESS = '@GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILED = '@GET_CATEGORY_FAILED';
export const GET_SELLER_PRODUCT_SUCCESS = '@GET_SELLER_PRODUCT_SUCCESS';
export const GET_SELLER_PRODUCT_FAILED = '@GET_SELLER_PRODUCT_FAILED';
export const GET_SELLER_ORDER_SUCCESS = '@GET_SELLER_ORDER_SUCCESS';
export const GET_SELLER_ORDER_FAILED = '@GET_SELLER_ORDER_FAILED';
export const GET_SELLER_DETAIL_ORDER_SUCCESS = '@GET_SELLER_DETAIL_ORDER_SUCCESS';
export const GET_SELLER_DETAIL_ORDER_FAILED = '@GET_SELLER_DETAIL_ORDER_FAILED';
export const PUT_STATUS_SELLER_ORDER_SUCCESS = '@PUT_STATUS_SELLER_ORDER_SUCCESS';
export const PUT_STATUS_SELLER_ORDER_FAILED = '@PUT_STATUS_SELLER_ORDER_FAILED';
export const POST_PRODUCT_SUCCESS = '@POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAILED = '@POST_PRODUCT_FAILED';
export const PUT_PRODUCT_SUCCESS = '@PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_FAILED = '@PUT_PRODUCT_FAILED';
export const DELETE_PRODUCT_SUCCESS = '@DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = '@DELETE_PRODUCT_FAILED';

export const GET_BANNER_SUCCESS = '@GET_BANNER_SUCCESS';
export const GET_BANNER_FAILED = '@GET_BANNER_FAILED';
