// Auth
export const LOGIN_SUCCESS = '@LOGIN_SUCCESS';
export const LOGIN_FAILED = '@LOGIN_FAILED';
export const REGISTER_SUCCESS = '@REGISTER_SUCCESS';
export const REGISTER_FAILED = '@LREGISTER_FAILED';

// Profile
export const GET_USER_SUCCESS = '@GET_USER_SUCCESS';
export const GET_USER_FAILED = '@GET_USER_FAILED';
export const UPDATE_USER_SUCCESS = '@UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = '@UPDATE_USER_FAILED';

// Global
export const LOGOUT = '@LOGOUT';
export const LOADING = '@LOADING';
export const REFRESH = '@REFRESH';

// Home buyer
export const GET_PRODUCT_SUCCESS = '@GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = '@GET_PRODUCT_FAILED';

export const GET_CATEGORY_SUCCESS = '@GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILED = '@GET_CATEGORY_FAILED';
